name: generate-pac-file

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
    paths:
      - rules.txt
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"

      - run: python -m pip install --upgrade pip
      - run: pip install genpac pyjsparser

      - run: genpac --format pac --user-rule-from ./rules.txt --pac-proxy "SOCKS5 127.0.0.1:9833" --output pac.js
      - run: python ./reverse.py

      - uses: josStorer/get-current-time@v2.1.1
        id: time
        with:
          format: yyyy-MM-DD

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: ${{ steps.time.outputs.formattedTime }} update pac.js"
          add: "['pac.js', 'merge.list']"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
